### ISSUE TITLE
Pip install fails due to deprecated sklearn package

### ISSUE THREAD

**Issue by cagrimunyas** [microsoft/vivainsights-py#11]
Repro :
- Create new Python env (Mine is 3.10.8)
- try "pip install vivainsights" or "pip3 install vivainsights"
- Error raises as 
```
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [18 lines of output]
      The 'sklearn' PyPI package is deprecated, use 'scikit-learn'
      rather than 'sklearn' for pip commands.

**Comment by martinctc** [comment]
Thanks @cagrimunyas - we'll have a look at this!

**Comment by sachinstl** [comment]
Hi @cagrimunyas ,

Kindly find [link](https://pypi.org/project/sklearn/) for scikit learn library / below screenshot for scikit learn library.

<img width="883" alt="image" src="https://github.com/microsoft/vivainsights-py/assets/56433553/f2aa77e5-d3c2-48f4-87f6-bab534aaac98">


There are changes for sklearn to scikit-learn. I tried reproducing the similar issue you are facing. Python 10.80 version is giving an error with scikit-learn  (we have to use sklearn instead of scikit-learn in python 10.80) but latest python version won't create any issue for scikit-learn.

Kindly update your python version and try installing the vivainsights.

Thanks

**Comment by cagrimunyas** [comment]
Thank you @sachinstl,
I've already installed it using the github repo itself. Inside vivainsights repo the requirement is typed as "scikit-learn" rather than the deprecated "sklearn". That's not the case for the pip package Please check: https://github.com/microsoft/vivainsights-py/blob/main/requirements.txt 

I have also tried installing it via pip with python 3.11.4, it raised the same error. Also the ss you shared says the opposite of what you wrote. Using "sklearn" instead of  "scikit-learn" will raise error in any python versins as it's depreceated, unless there is an env variable stated it in the last resort item. 

Also one of the commits acknowledges this https://github.com/microsoft/vivainsights-py/commit/beb59f7c28b4a9608530d09b989df6ebc03ee6fb. Simply pushing the latest version to the repo to the pip will resolve this.
